# Generated by Django 4.2.27 on 2026-01-30 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KSCertificationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='관리번호(바코드)')),
                ('name', models.TextField(verbose_name='한국산업표준명')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='시리얼번호')),
                ('ks_standard_number', models.CharField(blank=True, max_length=50, verbose_name='KS 규격번호')),
                ('certification_date', models.DateField(blank=True, null=True, verbose_name='인증일자')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='만료일자')),
                ('certification_body', models.CharField(blank=True, default='한국표준협회', max_length=100, verbose_name='인증기관')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='제조사')),
                ('manufacturer_country', models.CharField(blank=True, max_length=50, verbose_name='제조국')),
                ('status', models.CharField(choices=[('active', '사용중'), ('expired', '만료'), ('suspended', '중지'), ('discarded', '폐기')], default='active', max_length=20, verbose_name='상태')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='보관위치')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='수량')),
                ('unit', models.CharField(default='EA', max_length=20, verbose_name='단위')),
                ('inspection_required', models.BooleanField(default=False, verbose_name='점검필요')),
                ('last_inspection_date', models.DateField(blank=True, null=True, verbose_name='최근점검일')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='다음점검일')),
                ('remarks', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ks_items', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ks_items', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'verbose_name': 'KS 인증 품목',
                'verbose_name_plural': 'KS 인증 품목',
                'db_table': 'ks_certification_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KSCertificationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('register', '등록'), ('update', '수정'), ('scan', '스캔'), ('inspection', '점검'), ('status_change', '상태변경'), ('quantity_change', '수량변경')], max_length=20, verbose_name='작업유형')),
                ('action_description', models.TextField(verbose_name='작업내용')),
                ('previous_value', models.JSONField(blank=True, null=True, verbose_name='이전값')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='새값')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작업일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작업자')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='ks_certification.kscertificationitem', verbose_name='품목')),
            ],
            options={
                'verbose_name': 'KS 인증 이력',
                'verbose_name_plural': 'KS 인증 이력',
                'db_table': 'ks_certification_histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kscertificationitem',
            index=models.Index(fields=['barcode'], name='ks_certific_barcode_5df88f_idx'),
        ),
        migrations.AddIndex(
            model_name='kscertificationitem',
            index=models.Index(fields=['status'], name='ks_certific_status_dcdf0a_idx'),
        ),
        migrations.AddIndex(
            model_name='kscertificationitem',
            index=models.Index(fields=['certification_date'], name='ks_certific_certifi_3ff4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='kscertificationitem',
            index=models.Index(fields=['expiry_date'], name='ks_certific_expiry__c00462_idx'),
        ),
        migrations.AddIndex(
            model_name='kscertificationhistory',
            index=models.Index(fields=['item', '-created_at'], name='ks_certific_item_id_23f5be_idx'),
        ),
        migrations.AddIndex(
            model_name='kscertificationhistory',
            index=models.Index(fields=['action_type'], name='ks_certific_action__f2b6de_idx'),
        ),
    ]
