# Generated by Django 4.2.27 on 2026-01-19 15:44

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='사번')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='부서')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='직책')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('role', models.CharField(choices=[('admin', '관리자'), ('manager', '검토자'), ('user', '사용자')], default='user', max_length=20, verbose_name='역할')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='서명 이미지')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='마지막 접속 IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_at', models.DateTimeField(auto_now_add=True, verbose_name='로그인 시간')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('success', models.BooleanField(default=True, verbose_name='성공 여부')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name='실패 사유')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '로그인 이력',
                'verbose_name_plural': '로그인 이력',
                'ordering': ['-login_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '생성'), ('update', '수정'), ('delete', '삭제'), ('view', '조회'), ('approve', '승인'), ('reject', '반려'), ('export', '내보내기')], max_length=20, verbose_name='동작')),
                ('model_name', models.CharField(max_length=100, verbose_name='모델명')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='객체 ID')),
                ('object_repr', models.TextField(blank=True, verbose_name='객체 표현')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='변경 내용')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발생 시간')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '활동 로그',
                'verbose_name_plural': '활동 로그',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_ac_user_id_df2351_idx'), models.Index(fields=['model_name', 'object_id'], name='accounts_ac_model_n_91d77b_idx')],
            },
        ),
    ]
