# Generated by Django 4.2.27 on 2026-01-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_department_head',
            field=models.BooleanField(default=False, verbose_name='부서장 여부'),
        ),
    ]
