# Generated by Django 4.2.27 on 2026-01-20 06:09

from django.db import migrations, models
import django.db.models.deletion


def migrate_departments(apps, schema_editor):
    """기존 문자열 부서 데이터를 Department 모델로 변환"""
    User = apps.get_model('accounts', 'User')
    Department = apps.get_model('accounts', 'Department')
    
    # 기존 사용자들의 부서명 수집
    department_names = set()
    for user in User.objects.exclude(department='').exclude(department__isnull=True):
        if user.department:
            department_names.add(user.department)
    
    # Department 객체 생성
    department_map = {}
    for dept_name in department_names:
        if dept_name:
            dept, created = Department.objects.get_or_create(
                name=dept_name,
                defaults={'code': dept_name[:20].upper().replace(' ', '_')}
            )
            department_map[dept_name] = dept
    
    # 사용자의 부서를 ForeignKey로 업데이트
    for user in User.objects.exclude(department='').exclude(department__isnull=True):
        if user.department and user.department in department_map:
            user.department_new = department_map[user.department]
            user.save()


def reverse_migrate_departments(apps, schema_editor):
    """역방향 마이그레이션: Department를 문자열로 변환"""
    User = apps.get_model('accounts', 'User')
    Department = apps.get_model('accounts', 'Department')
    
    for user in User.objects.exclude(department_new__isnull=True):
        if user.department_new:
            user.department = user.department_new.name
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_department_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='부서명')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='부서코드')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '부서',
                'verbose_name_plural': '부서',
                'ordering': ['name'],
            },
        ),
        # 임시 필드 추가 (문자열 부서 데이터 보존)
        migrations.AddField(
            model_name='user',
            name='department_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.department', verbose_name='부서'),
        ),
        # 데이터 마이그레이션
        migrations.RunPython(migrate_departments, reverse_migrate_departments),
        # 기존 department 필드 제거
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        # department_new를 department로 이름 변경
        migrations.RenameField(
            model_name='user',
            old_name='department_new',
            new_name='department',
        ),
    ]
