# Generated by Django 4.2.27 on 2026-01-19 15:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(max_length=50, unique=True, verbose_name='문서번호')),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('revision', models.CharField(default='0', max_length=10, verbose_name='개정번호')),
                ('content_data', models.JSONField(default=dict, help_text='템플릿 필드에 대응하는 데이터', verbose_name='문서 내용')),
                ('status', models.CharField(choices=[('draft', '작성중'), ('pending_review', '검토 대기'), ('pending_approval', '승인 대기'), ('approved', '승인 완료'), ('rejected', '반려'), ('obsolete', '폐기')], default='draft', max_length=20, verbose_name='상태')),
                ('is_locked', models.BooleanField(default=False, verbose_name='잠금')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='제출일')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='검토일')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='documents/pdf/%Y/%m/', verbose_name='PDF 파일')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_documents', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
            ],
            options={
                'verbose_name': '문서',
                'verbose_name_plural': '문서',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='코드')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('prefix', models.CharField(max_length=20, verbose_name='문서번호 접두사')),
                ('next_number', models.IntegerField(default=1000, verbose_name='다음 문서번호')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '문서 카테고리',
                'verbose_name_plural': '문서 카테고리',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='템플릿명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('fields_schema', models.JSONField(default=dict, help_text='문서에 필요한 필드 정의 (JSON 형식)', verbose_name='필드 스키마')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='document_templates/', validators=[django.core.validators.FileExtensionValidator(['html', 'docx'])], verbose_name='템플릿 파일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='버전')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='documents.documentcategory', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '문서 템플릿',
                'verbose_name_plural': '문서 템플릿',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='동작')),
                ('from_status', models.CharField(blank=True, max_length=30, verbose_name='이전 상태')),
                ('to_status', models.CharField(blank=True, max_length=30, verbose_name='이후 상태')),
                ('comment', models.TextField(blank=True, verbose_name='비고')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='documents.document', verbose_name='문서')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '문서 이력',
                'verbose_name_plural': '문서 이력',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('general', '일반'), ('review', '검토'), ('rejection', '반려 사유'), ('approval', '승인')], default='general', max_length=20, verbose_name='유형')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.document', verbose_name='문서')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '문서 코멘트',
                'verbose_name_plural': '문서 코멘트',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/attachments/%Y/%m/', verbose_name='파일')),
                ('filename', models.CharField(max_length=255, verbose_name='파일명')),
                ('file_size', models.IntegerField(default=0, verbose_name='파일 크기')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.document', verbose_name='문서')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='업로더')),
            ],
            options={
                'verbose_name': '첨부파일',
                'verbose_name_plural': '첨부파일',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentcategory', verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='document',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='검토자'),
        ),
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documenttemplate', verbose_name='템플릿'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_number'], name='documents_d_documen_dbcf06_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', 'created_at'], name='documents_d_status_64808e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_by', 'status'], name='documents_d_created_879792_idx'),
        ),
    ]
