# Generated by Django 4.2.27 on 2026-02-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='excel_file',
            field=models.FileField(blank=True, help_text='직접 작성한 엑셀 문서 업로드', null=True, upload_to='documents/excel/%Y/%m/', verbose_name='엑셀 파일'),
        ),
    ]
