# Generated by Django 4.2.27 on 2026-02-10 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_seed_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='document_templates/', validators=[django.core.validators.FileExtensionValidator(['html', 'docx', 'xlsx', 'xls', 'hwp'])], verbose_name='템플릿 파일'),
        ),
    ]
