# Generated by Django 4.2.27 on 2026-01-19 15:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count_number', models.CharField(max_length=50, unique=True, verbose_name='실사번호')),
                ('status', models.CharField(choices=[('draft', '작성중'), ('in_progress', '진행중'), ('completed', '완료'), ('cancelled', '취소')], default='draft', max_length=20, verbose_name='상태')),
                ('count_date', models.DateField(verbose_name='실사일')),
                ('remarks', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_counts', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_counts', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '재고 실사',
                'verbose_name_plural': '재고 실사',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_code', models.CharField(max_length=50, unique=True, verbose_name='품목 코드')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='바코드')),
                ('name', models.CharField(max_length=200, verbose_name='품목명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('item_type', models.CharField(choices=[('material', '자재'), ('product', '제품'), ('consumable', '소모품'), ('equipment', '장비')], default='material', max_length=20, verbose_name='품목 유형')),
                ('unit', models.CharField(default='EA', max_length=20, verbose_name='단위')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='규격')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='제조사')),
                ('supplier', models.CharField(blank=True, max_length=100, verbose_name='공급업체')),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='현재 수량')),
                ('safety_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='안전재고')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='단가')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/items/', verbose_name='이미지')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('iso_document', models.CharField(blank=True, max_length=50, verbose_name='ISO 문서번호')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '재고 품목',
                'verbose_name_plural': '재고 품목',
                'ordering': ['item_code'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='창고 코드')),
                ('name', models.CharField(max_length=100, verbose_name='창고명')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
            ],
            options={
                'verbose_name': '창고',
                'verbose_name_plural': '창고',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', '안전재고 미달'), ('out_of_stock', '재고 소진'), ('overstock', '과잉 재고')], max_length=20, verbose_name='알림 유형')),
                ('message', models.TextField(verbose_name='알림 메시지')),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='현재 수량')),
                ('threshold_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='기준 수량')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='해결됨')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='해결일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.inventoryitem', verbose_name='품목')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='해결자')),
            ],
            options={
                'verbose_name': '재고 알림',
                'verbose_name_plural': '재고 알림',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='위치 코드')),
                ('name', models.CharField(max_length=100, verbose_name='위치명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='바코드')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse', verbose_name='창고')),
            ],
            options={
                'verbose_name': '위치',
                'verbose_name_plural': '위치',
                'ordering': ['warehouse', 'code'],
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='카테고리 코드')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.itemcategory', verbose_name='상위 카테고리')),
            ],
            options={
                'verbose_name': '품목 카테고리',
                'verbose_name_plural': '품목 카테고리',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.itemcategory', verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_items', to=settings.AUTH_USER_MODEL, verbose_name='등록자'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='default_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.location', verbose_name='기본 위치'),
        ),
        migrations.CreateModel(
            name='InventoryCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='시스템 수량')),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='실사 수량')),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='차이')),
                ('remarks', models.TextField(blank=True, verbose_name='비고')),
                ('counted_at', models.DateTimeField(blank=True, null=True, verbose_name='실사일시')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='실사자')),
                ('inventory_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorycount', verbose_name='실사')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem', verbose_name='품목')),
            ],
            options={
                'verbose_name': '실사 품목',
                'verbose_name_plural': '실사 품목',
            },
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_counts', to='inventory.warehouse', verbose_name='창고'),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_number', models.CharField(max_length=50, unique=True, verbose_name='거래번호')),
                ('transaction_type', models.CharField(choices=[('in', '입고'), ('out', '출고'), ('adjust', '조정'), ('transfer', '이동'), ('return', '반품')], max_length=20, verbose_name='거래 유형')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='수량')),
                ('before_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='거래 전 수량')),
                ('after_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='거래 후 수량')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='참조번호')),
                ('remarks', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='거래일시')),
                ('scanned_barcode', models.CharField(blank=True, max_length=100, verbose_name='스캔된 바코드')),
                ('scan_device', models.CharField(blank=True, max_length=100, verbose_name='스캔 장치')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.inventoryitem', verbose_name='품목')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.location', verbose_name='위치')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_transactions', to='inventory.location', verbose_name='이동 위치')),
            ],
            options={
                'verbose_name': '재고 거래',
                'verbose_name_plural': '재고 거래',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_number'], name='inventory_s_transac_6201c3_idx'), models.Index(fields=['item', 'created_at'], name='inventory_s_item_id_987ed8_idx'), models.Index(fields=['transaction_type', 'created_at'], name='inventory_s_transac_fce13a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['barcode'], name='inventory_i_barcode_c7bf0e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['item_code'], name='inventory_i_item_co_d93027_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['name'], name='inventory_i_name_9b5824_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorycountitem',
            unique_together={('inventory_count', 'item')},
        ),
    ]
