# Generated by Django 4.2.27 on 2026-01-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='inspection_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='점검예정일자'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='inspection_required',
            field=models.BooleanField(default=False, verbose_name='점검여부'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='시리얼번호'),
        ),
    ]
