# Generated by Django 4.2.27 on 2026-01-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_inspection_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='accuracy',
            field=models.CharField(blank=True, max_length=50, verbose_name='정확도'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='calibration_agency',
            field=models.CharField(blank=True, max_length=100, verbose_name='검정기관'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='calibration_cycle_months',
            field=models.IntegerField(blank=True, null=True, verbose_name='검정주기(개월)'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='calibration_required',
            field=models.BooleanField(default=False, verbose_name='검정필요'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='certification_body',
            field=models.CharField(blank=True, max_length=100, verbose_name='인증기관'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='certification_date',
            field=models.DateField(blank=True, null=True, verbose_name='인증일자'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='certification_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='인증상태'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='사용부서'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='equipment_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='장비상태'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='장비유형'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='만료일자'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='issued_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='출고수량'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='ks_standard_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='KS규격번호'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_calibration_date',
            field=models.DateField(blank=True, null=True, verbose_name='최근검정일'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='measurement_range',
            field=models.CharField(blank=True, max_length=100, verbose_name='측정범위'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='model_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='모델번호'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='next_calibration_date',
            field=models.DateField(blank=True, null=True, verbose_name='다음검정일'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='구매일'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='구매가격'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='received_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='입고수량'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=50, verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='보증만료일'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('material', '자재'), ('product', '제품'), ('consumable', '소모품'), ('equipment', '장비'), ('ks_certification', 'KS인증'), ('measurement', '계측장비'), ('parts', '사내부품'), ('supplies', '사내소모품')], default='material', max_length=20, verbose_name='품목 유형'),
        ),
    ]
