# Generated by Django 4.2.27 on 2026-01-30 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_inventoryitem_accuracy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelMasterDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('ks_cert', 'KS 인증 사내문서 관리대장'), ('measurement', '계측장비 재고조사 관리대장'), ('parts', '재고관리 리스트 (PRT)'), ('supplies', '재고관리 리스트 (SUP)')], max_length=20, unique=True, verbose_name='문서유형')),
                ('title', models.CharField(max_length=200, verbose_name='문서제목')),
                ('file_path', models.CharField(max_length=500, verbose_name='파일경로')),
                ('sheet_name', models.CharField(default='Sheet1', max_length=100, verbose_name='시트명')),
                ('header_row', models.IntegerField(default=6, verbose_name='헤더행')),
                ('data_start_row', models.IntegerField(default=8, verbose_name='데이터시작행')),
                ('barcode_column', models.IntegerField(default=2, verbose_name='바코드컬럼')),
                ('name_column', models.IntegerField(default=5, verbose_name='이름컬럼')),
                ('extra_columns', models.JSONField(blank=True, default=dict, verbose_name='추가컬럼정보')),
                ('total_items', models.IntegerField(default=0, verbose_name='총항목수')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='최종수정일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
            options={
                'verbose_name': '엑셀 마스터 문서',
                'verbose_name_plural': '엑셀 마스터 문서',
                'db_table': 'excel_master_documents',
            },
        ),
        migrations.CreateModel(
            name='ExcelUpdateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=100, verbose_name='바코드')),
                ('action', models.CharField(max_length=50, verbose_name='작업')),
                ('updates', models.JSONField(default=dict, verbose_name='변경내용')),
                ('previous_values', models.JSONField(blank=True, default=dict, verbose_name='이전값')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작업일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작업자')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_logs', to='inventory.excelmasterdocument', verbose_name='문서')),
            ],
            options={
                'verbose_name': '엑셀 업데이트 로그',
                'verbose_name_plural': '엑셀 업데이트 로그',
                'db_table': 'excel_update_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
